# Generated by Django 2.0.13 on 2019-09-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='input',
            new_name='Inputs',
        ),
    ]
